author: Gerhard
description: Spatial professional and walker (he/him)
markdown: kramdown
permalink: /:title/
title: Ground Truth
url: "https://groundtruth.gerhardla.nz"

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false
